### ISSUE TITLE
Prepare word trends for Riksdagens Protokoll  1867-2019 (KB-labb data)

### ISSUE THREAD

**Issue by roger-mahler** [welfare-state-analytics/westac_data#1]
Detailed steps to produce a corpus for 1867 to 2019:

A tagged corpus for the period 1900 to 2019 already exists (created using Sparv v4.1). The raw text files for 1867 to 1899 are also already available (downloaded from KB-labb using their API). 

These protocols from 1867 to 1899 are tagged using Språkbankens Sparv v4 pipeline with the Swedish 1800 language variety. Since this variety currently only appears to be available in the `dev` branch of the Sparv source code, a development install of the pipeline is needed:

```bash
cd "work-dir"
git clone git@github.com:spraakbanken/sparv-pipeline
cd sparv-pipeline
git checkout dev
python -m venv .venv
source ./.venv/bin/activate
```

Prepare work folder for tagging:

```bash
mkdir -p riksprot_1867-1899/source
cd riksprot_1867-1899/source
unzip "path-to-zip-with-text-files"/riksdagens_protokoll_1867-1899.zip
cd ..
```

Add Sparv `config.yaml` configuration file to `riksprot_1867-1899` folder:

```yaml
metadata:
    id: swe-1800
    language: swe-1800
    description:
        eng: |
            PoS tagging of riksprot 1878-1899.

import:
  importer: text_import:parse

export:
    annotations:
        - <token>:hunpos.pos
        - <token>:hist.baseform
        - <token>:saldo.baseform
    default:
        - csv_export:csv

segment:
  sentence_segmenter: linebreaks
```
Run `sparv` from `riksprot_1867-1899` folder (will take several hours to complete):

```bash
sparv run --cores 12
```

Add resulting CSV files found in exports/csv to a single zip archive `riksdagens_protokoll_1867-1899.sparv.csv.zip`.

```bash
cd exports/csv
zip -9 riksdagens_protokoll_1867-1899.sparv.csv.zip *.csv
```

Use `zipmerge` to create a single complete archive for the period 1867-2019.

```bash
zipmerge riksdagens_protokoll_1867-2019.sparv.csv.zip \
      "path-to-zip"/riksdagens_protokoll_1867-1899.sparv.csv.zip
      "path-to-zip"/riksdagens_protokoll_1900-2019.sparv.csv.zip
```

**Comment by roger-mahler** [comment]
Detailed steps on how to create a vectorized corpus from tagged corpus:

1. Create a sandboxed virtual environment and install `humlab-penelope`.
```bash
cd "some-work-dir"
mkdir sandboxed_vectorize
cd sandboxed_vectorize
python -m venv venv
source venv/bin/activate
pip install humlab-penelope
```
2. Create a corpus config file `riksprot_1867-2019.yml` (se content below).
3. Run vectorizer:
```bash
 nohup vectorize \
        --pos-includes "|JJ|AB|HA|IE|IN|PL|KN|SN|NN|PM|RG|RO|UO|PP|DT|HD|HP|HS|PN|PS|PC|VB|" \
        --pos-excludes "|MAD|MID|PAD|" \
        --lemmatize --tf-threshold 5 --no-keep-symbols --no-keep-numerals --to-lower \
        --enable-checkpoint \
         "path-to-corpus-config"/riksprot_1867-2019.yml \
         "path-to-tagged-corpus"/riksdagens-protokoll.1867-2019.sparv4.csv.zip \
         "path-to-target-data"/shared word_trends_1867-2019 &
```

Note: "path-to-target" must be `/data/westac/shared` if corpus should be accessible from westac-lab.

**Comment by roger-mahler** [comment]
Sample corpus config:

```yaml
corpus_name: riksdagens-protokoll-1867-2919
corpus_pattern: '*sparv4.csv.zip'
corpus_type: 3
language: swedish
checkpoint_opts:
    content_type_code: 1
    sep: "\t"
    quoting: 3
    document_index_name: null
    document_index_sep: null
    text_column: token
    lemma_column: baseform
    pos_column: pos
    extra_columns: []
    custom_serializer_classname: penelope.pipeline.sparv.convert.SparvCsvSerializer
    deserialize_processes: 6
    deserialize_chunksize: 4
    feather_folder: /data/westac/shared/checkpoints/riksdagens-protokoll.1867-2019.sparv4.csv_feather
    index_column: null
pipelines:
  tagged_frame_pipeline: penelope.pipeline.sparv.pipelines.to_tagged_frame_pipeline
pipeline_payload:
  source: riksdagens-protokoll.1867-2019.sparv4.csv.zip
  document_index_source: null
  document_index_sep: "\t"
  filenames: null
  memory_store:
    lang: se
    tagger: Sparv
    sparv_version: 4
    text_column: token
    lemma_column: baseform
    pos_column: pos
  pos_schema_name: SUC
filter_opts:
text_reader_opts:
  as_binary: false
  filename_fields:
   - "year:prot\\_(\\d{4}).*"
   - "year2:prot_\\d{4}(\\d{2})__*"
   - "number:prot_\\d+[afk_]{0,4}__(\\d+).*"
  filename_filter: null
  filename_pattern: '*.csv'
  index_field: null
  sep: "\t"
  quoting: 3


```
